const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { spawn } = require('node:child_process');
const fixture = vm.createContext({});
vm.runInContext(fs.readFileSync('fixtures/demo-data.js', 'utf8') + ';globalThis.stones=DEMO_STONES', fixture);
const server = spawn('python3', ['-u', '-m', 'http.server', '8139']);
process.on('exit', () => server.kill());
(async () => {
  await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => reject(Error('Server exited: ' + code))); });
  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await context.addInitScript(() => { Date.now = () => Date.parse('2026-10-06T12:00:00Z'); });
    await context.route('http://127.0.0.1:8787/**', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify(route.request().method() === 'GET' ? { stones: fixture.stones } : { views: 1, ok: true }) }));
    await context.route('https://tile.openstreetmap.org/**', route => route.abort());
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    for (const [width, columns] of [[1440, 5], [1098, 5], [1024, 5], [900, 4], [768, 3], [600, 3], [480, 3], [375, 3], [320, 3]]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.goto('http://127.0.0.1:8139');
      await page.locator('.journey-card').first().waitFor();
      assert.equal(await page.locator('.journey-card').count(), 14);
      assert.equal(await page.locator('#world-map .map-stone-image').count(), 14);
      assert.equal(await page.locator('.card-actions, [data-map-path], #explore .section-heading').count(), 0);
      assert.equal(await page.locator('#stone-list').isVisible(), false);
      assert.equal(await page.locator('#total-stones').textContent(), '14');
      assert.equal(await page.locator('.stone-card-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), columns, `Columns at ${width}`);
      await page.waitForFunction(expected => document.querySelectorAll('.journey-card:not([hidden])').length === expected, Math.min(14, columns * 3));
      assert.equal(await page.locator('#stone-count').textContent(), `Showing ${Math.min(14, columns * 3)} of 14 stones`);
      assert.equal(await page.locator('#show-more-stones').isVisible(), columns * 3 < 14);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `No overflow at ${width}`);
      assert.ok(await page.locator('.journey-card').evaluateAll(cards => cards.every(card => card.scrollWidth <= card.clientWidth)), `Cards fit at ${width}`);
      await page.locator('.journey-card:visible').last().scrollIntoViewIfNeeded();
      await page.waitForFunction(() => [...document.querySelectorAll('.journey-card:not([hidden]) .card-portrait img')].every(img => img.complete && img.naturalWidth > 0));
      if ([1440, 1098, 375, 320].includes(width)) await page.locator('#explore').screenshot({ style: ".site-header, .skip-link { visibility: hidden !important; }", path: `/tmp/livingstones-cards-${width}.png` });
    }
    // Rotate the same viewport back and forth to exercise live media query changes.
    for (const [width, height, columns] of [[375, 812, 3], [812, 375, 5], [844, 390, 5], [932, 430, 5], [568, 320, 5], [320, 568, 3]]) {
      await page.setViewportSize({ width, height });
      assert.equal(await page.locator('.stone-card-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), columns, `Columns at ${width} × ${height}`);
      await page.waitForFunction(expected => document.querySelectorAll('.journey-card:not([hidden])').length === expected, Math.min(14, columns * 3));
      assert.equal(await page.locator('#stone-count').textContent(), `Showing ${Math.min(14, columns * 3)} of 14 stones`);
      assert.equal(await page.locator('#show-more-stones').isVisible(), columns * 3 < 14);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `No overflow at ${width} × ${height}`);
      assert.ok(await page.locator('.journey-card').evaluateAll(cards => cards.every(card => card.scrollWidth <= card.clientWidth)), 'Rotated cards fit');
      assert.ok(await page.locator('.journey-totals').evaluate(el => el.scrollWidth <= el.clientWidth), 'Larger statistics fit');
      assert.ok(await page.locator('.journey-totals dd').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 24), 'Statistic values are larger');
      assert.ok(await page.locator('.journey-totals dt').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 13), 'Statistic labels are larger');
      if (width === 812) await page.locator('#explore').screenshot({ style: ".site-header, .skip-link { visibility: hidden !important; }", path: '/tmp/livingstones-cards-landscape.png' });
      if (width === 320) await page.locator('.journey-totals').screenshot({ path: '/tmp/livingstones-larger-statistics.png' });
    }
    await page.locator('#show-more-stones').click();
    assert.equal(await page.locator('.journey-card:visible').count(), 14);
    assert.equal(await page.locator('#stone-count').textContent(), 'Showing 14 of 14 stones');
    assert.equal(await page.locator('#show-more-stones').isVisible(), false);
    assert.equal(await page.locator('.journey-card').nth(9).evaluate(el => el === document.activeElement), true);
    await page.locator('#filters-toggle').click();
    await page.locator('#stone-search').fill('Luna');
    assert.equal(await page.locator('#stone-count').textContent(), 'Showing 1 of 1 stone');
    await page.locator('#stone-search').fill('');
    assert.equal(await page.locator('.journey-card:visible').count(), 9);
    const mapView = await page.evaluate(() => { const map = mapInstances.get('world-map').map; return { zoom: map.getZoom(), center: map.getCenter() }; });
    await page.locator('#map-toggle').click();
    assert.equal(await page.locator('#world-map').isVisible(), false);
    assert.equal(await page.locator('#map-toggle').getAttribute('aria-expanded'), 'false');
    assert.equal(await page.locator('.journey-totals').isVisible(), true);
    assert.equal(await page.locator('#stone-cards').isVisible(), true);
    assert.equal(await page.locator('.map-hint').count(), 0);
    await page.locator('#map-toggle').focus();
    await page.keyboard.press('Enter');
    await page.locator('#world-map').waitFor();
    await page.waitForTimeout(100);
    const reopenedView = await page.evaluate(() => { const map = mapInstances.get('world-map').map; return { zoom: map.getZoom(), center: map.getCenter() }; });
    assert.deepEqual(reopenedView, mapView, 'Reopening preserves the map view');
    await page.locator('#map-toggle').click();
    await page.evaluate(() => renderOverview());
    await page.locator('#map-toggle').click();
    await page.locator('#world-map').waitFor();
    await page.waitForTimeout(100);
    assert.equal(await page.locator('#world-map .map-stone-image').count(), 14);
    await page.waitForFunction(() => document.querySelector('.map-stone-image').getBoundingClientRect().width > 40 && document.querySelector('.map-stone-image').getBoundingClientRect().width < 49); // The SVG includes transparent margins around the enlarged stone.
    await page.locator('#stone-search').fill('Luna');
    assert.equal(await page.locator('.journey-card').count(), 1);
    assert.equal(await page.locator('.journey-card h3').textContent(), 'Little Luna');
    await page.locator('#stone-search').fill('Vienna');
    assert.ok((await page.locator('.journey-card').count()) > 0);
    assert.ok((await page.locator('.card-city').allTextContents()).every(city => city === 'Vienna'));
    await page.locator('#stone-search').fill('no such stone');
    assert.equal(await page.locator('#stone-empty').isVisible(), true);
    assert.equal(await page.locator('#total-stones').textContent(), '14', 'Search never changes overall statistics');
    await page.locator('#stone-search').fill('');
    await page.locator('[data-stone-sort="age"]').click();
    assert.equal(await page.locator('[data-stone-sort="age"]').getAttribute('aria-pressed'), 'true');
    assert.deepEqual(await page.locator('.journey-card').evaluateAll(cards => cards.map(card => card.dataset.stone)), ['J10', 'A1', 'N14', 'D4', 'F6', 'I9', 'B2', 'G7', 'E5', 'L12', 'H8', 'K11', 'M13', 'C3']);
    await page.locator('[data-stone-view="list"]').click();
    assert.equal(await page.locator('.stone-table th').nth(2).getAttribute('aria-sort'), 'descending');
    assert.deepEqual(await page.locator('.stone-row').evaluateAll(rows => rows.map(row => row.dataset.stone)), ['J10', 'A1', 'N14', 'D4', 'F6', 'I9', 'B2', 'G7', 'E5', 'L12', 'H8', 'K11', 'M13', 'C3']);
    await page.locator('[data-stone-view="cards"]').click();
    await page.locator('[data-stone-sort="distance"]').click();
    assert.ok(await page.evaluate(() => {
      const distances = [...document.querySelectorAll('.card-facts > div:first-child dd')].map(el => Number(el.textContent.replace(/[^\d]/g, '')));
      return distances.every((distance, index) => !index || distance <= distances[index - 1]);
    }));
    await page.locator('[data-stone-view="list"]').click();
    assert.equal(await page.locator('#stone-list').isVisible(), true);
    assert.equal(await page.locator('#stone-cards').isVisible(), false);
    assert.equal(await page.locator('th[aria-sort="none"]').count(), 1);
    await page.locator('[data-stone-view="cards"]').click();
    await page.locator('[data-stone-sort="recent"]').click();
    assert.equal(await page.locator('.journey-card h3').first().textContent(), 'Mountain Whisper');
    await page.locator('.journey-card').first().locator('.card-facts').click();
    await page.locator('dialog[open]').waitFor();
    assert.match(await page.locator('#detail-title').textContent(), /Mountain Whisper/);
    assert.equal(await page.locator('#journey-map .leaflet-marker-icon').count(), 5);
    await page.locator('#close-detail').click();
    await page.locator('dialog').waitFor({ state: 'hidden' });
    await page.locator('.journey-card').first().focus();
    await page.keyboard.press('Enter');
    await page.locator('dialog[open]').waitFor();
    assert.match(await page.locator('#detail-title').textContent(), /Mountain Whisper/);
    await page.locator('#close-detail').click();
    await page.locator('dialog').waitFor({ state: 'hidden' });
    await page.evaluate(() => {
      const stone = stoneRepository.get('A1');
      stone.finds.at(-1).city = 'Prague';
      stone.finds.at(-1).country = 'Czechia';
      renderOverview();
    });
    const flag = page.locator('.journey-card[data-stone="A1"] .card-location .country-flag');
    assert.equal(await flag.getAttribute('alt'), 'Czechia');
    await flag.evaluate(img => img.decode());
    assert.ok(await flag.evaluate(img => img.naturalWidth > 0));
    await page.locator('[data-stone-view="list"]').click();
    assert.equal(await page.locator('.stone-row[data-stone="A1"] .country-flag').getAttribute('alt'), 'Czechia');
    await page.locator('[data-stone-view="cards"]').click();
    assert.deepEqual(await page.locator('.stone-view-switch button').allTextContents(), ['Cards', 'List']);
    assert.equal(await page.locator('.stone-view-switch a, #active-stones').count(), 0);
    await page.locator('#world-map .map-stone-image').evaluateAll(images => Promise.all(images.map(img => img.decode())));
    await page.locator('#world-map .leaflet-marker-icon').first().focus();
    assert.equal(await page.locator('#world-map .leaflet-tooltip').count(), 0);
    assert.doesNotMatch(await page.locator('#world-map').innerText(), /undefined/);
    await page.keyboard.press('Enter');
    await page.locator('.stone-overview-popup').waitFor();
    assert.deepEqual(errors, []);
    console.log('Card grid, search, age/distance/recency sorting, map without name labels, view switches and whole-card mouse/keyboard navigation and Czech flags passed at eight widths, with phone rotation and compact statistics.');
  } finally { await browser.close(); server.kill(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
