const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { spawn } = require('node:child_process');
const fixture = vm.createContext({});
vm.runInContext(fs.readFileSync('fixtures/demo-data.js', 'utf8') + ';globalThis.stones=DEMO_STONES', fixture);
const server = spawn('python3', ['-u', '-m', 'http.server', '8139']);
process.on('exit', () => server.kill());
(async () => {
  await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => reject(Error('Server exited: ' + code))); });
  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await context.addInitScript(() => { Date.now = () => Date.parse('2026-10-06T12:00:00Z'); });
    await context.route('http://127.0.0.1:8787/**', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify(route.request().method() === 'GET' ? { stones: fixture.stones } : { views: 1, ok: true }) }));
    await context.route('https://tile.openstreetmap.org/**', route => route.abort());
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    for (const [width, columns] of [[1440, 5], [1024, 4], [768, 3], [600, 3], [375, 2], [320, 2]]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.goto('http://127.0.0.1:8139');
      await page.locator('.journey-card').first().waitFor();
      assert.equal(await page.locator('.journey-card').count(), 9);
      assert.equal(await page.locator('#stone-list').isVisible(), false);
      assert.equal(await page.locator('#total-stones').textContent(), '9');
      assert.equal(await page.locator('.stone-card-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), columns, `Columns at ${width}`);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `No overflow at ${width}`);
      assert.ok(await page.locator('.journey-card').evaluateAll(cards => cards.every(card => card.scrollWidth <= card.clientWidth)), `Cards fit at ${width}`);
      await page.locator('.journey-card').last().scrollIntoViewIfNeeded();
      await page.waitForFunction(() => [...document.querySelectorAll('.card-portrait img')].every(img => img.complete && img.naturalWidth > 0));
      if ([1440, 768, 375].includes(width)) await page.locator('#explore').screenshot({ style: ".site-header, .skip-link { visibility: hidden !important; }", path: `/tmp/livingstones-cards-${width}.png` });
    }
    await page.locator('#stone-search').fill('Luna');
    assert.equal(await page.locator('.journey-card').count(), 1);
    assert.equal(await page.locator('.journey-card h3').textContent(), 'Little Luna');
    await page.locator('#stone-search').fill('Vienna');
    assert.ok((await page.locator('.journey-card').count()) > 0);
    assert.ok((await page.locator('.card-city').allTextContents()).every(city => city === 'Vienna'));
    await page.locator('#stone-search').fill('no such stone');
    assert.equal(await page.locator('#stone-empty').isVisible(), true);
    assert.equal(await page.locator('#total-stones').textContent(), '9', 'Search never changes overall statistics');
    await page.locator('#stone-search').fill('');
    await page.evaluate(() => { stoneRepository.get('B2').finds.at(-1).date = '2026-01-01'; });
    await page.locator('#active-stones').click();
    assert.equal(await page.locator('.journey-card').count(), 8);
    assert.equal(await page.locator('#active-stones').getAttribute('aria-pressed'), 'true');
    await page.locator('#active-stones').click();
    assert.equal(await page.locator('.journey-card').count(), 9);
    await page.locator('[data-stone-sort="distance"]').click();
    assert.ok(await page.evaluate(() => {
      const distances = [...document.querySelectorAll('.card-facts > div:first-child dd')].map(el => Number(el.textContent.replace(/[^\d]/g, '')));
      return distances.every((distance, index) => !index || distance <= distances[index - 1]);
    }));
    await page.locator('[data-stone-view="list"]').click();
    assert.equal(await page.locator('#stone-list').isVisible(), true);
    assert.equal(await page.locator('#stone-cards').isVisible(), false);
    assert.equal(await page.locator('th[aria-sort="none"]').count(), 1);
    await page.locator('[data-stone-view="cards"]').click();
    await page.locator('[data-stone-sort="recent"]').click();
    assert.equal(await page.locator('.journey-card h3').first().textContent(), 'Hello Pebble');
    await page.locator('.journey-card').first().locator('.card-details').click();
    await page.locator('dialog[open]').waitFor();
    assert.match(await page.locator('#detail-title').textContent(), /Hello Pebble/);
    assert.equal(await page.locator('#journey-map .leaflet-marker-icon').count(), 5);
    await page.locator('#close-detail').click();
    await page.locator('dialog').waitFor({ state: 'hidden' });
    await page.locator('.journey-card').first().locator('[data-map-path]').click();
    await page.locator('dialog[open]').waitFor();
    await page.waitForTimeout(400);
    assert.equal(await page.locator('#journey-map').isVisible(), true);
    assert.ok(await page.locator('#journey-map').evaluate(el => { const map = el.getBoundingClientRect(), dialog = el.closest('dialog').getBoundingClientRect(); return map.top >= dialog.top && map.bottom <= dialog.bottom; }), 'Map Path brings the route into view');
    await page.locator('#close-detail').click();
    await page.locator('dialog').waitFor({ state: 'hidden' });
    await page.locator('.stone-view-switch a').click();
    assert.equal(new URL(page.url()).hash, '#world');
    assert.deepEqual(errors, []);
    console.log('Card grid, search, active filter, route sorting, view switches and story/map actions passed at six widths.');
  } finally { await browser.close(); server.kill(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
